version: "3.9"
services:
  react:
    image: geetha20/react-frontend
    container_name: react
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - springboot

  springboot:
    image: "geetha20/springboot:${MONGO_URL}"
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"