version: "3.9"
services:
  react:
    image: geetha20/react-frontend
    container_name: react
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - springboot
      - mongodb

  springboot:
    image: geetha20/springboot
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/EmployeeDB
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
