name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #-
    #    name: Checkout
    #    uses: actions/checkout@v3
    #    with:
    #      path: action
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - uses: docker/setup-buildx-action@v1
    #- uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:react-frontend"
        push: true
        tags: ${{secrets.DOCKER_USER}}/reactapp:${{ steps.commit.outputs.short }}
    #-
    #  name: Build
    #  run: |
    #       cd react-frontend
    #       docker build . --file Dockerfile -t ${{secrets.DOCKER_USER}}/reactapp:${{ steps.commit.outputs.short }}
           
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/reactapp:${{ steps.commit.ou${{secrets.DOCKER_USER}}/reactapp:tputs.short }}
           
        
